- jws/jws.go
As mentioned in https://github.com/lestrrat/go-jwx/issues/3, I thought `VerifyWithJWK` method should accept `sig` use value to verify JWS.
How do you think about it?
> accept "sig" use of JWK for verifying

- jwk/ecdsa.go
- jwk/jwk_test.go
Setting the bytes of an ECDSA coordinate can result in a length mismatch
if the octet string is not properly padded.
> Fix: Serialization edge case

- jwt/interface.go
According to the spec document the JWT ID is in the "jti" claim, not "jtu".
> Looks like a typo, "jtu" for "jti".

- jwk/header.go
- jwk/header_test.go
Value of key_ops of accessor was added because it was not implemented.
If the dare of unsupported, please close this PR.
> Add key_ops support for jwk/Key (g|s)etter interface

- jwk/ecdsa.go
- jwk/ecdsa_test.go
The jwk.NewEcdsaPublicKey and jwk.NewEcdsaPrivateKey functions
are not initializing the EssentialHeader of the EcdsaPublicKey struct
which means they do not have an initialized KeyType (jwa.EC) and
attempts to set header parameters with Set() cause a panic. This
initialization is done correctly for RSA keys.
This commit fixes the initializion of the EssentialHeader for JWK
ECDSA keys and sets their KeyType parameter to jwa.EC. A unit test
is also implemented to verify correct behavior.
> Initialize the EssentialHeader of ECDSA JWKs.

- jwt/jwt.go
- jwt/jwt_test.go
The Construct() method for a JWT EssentialClaim has an incorrect
error check comparison (simply a != instead of an ==) for the
GetString() of the "nbf" parameter. This causes the nbf value to
not be parsed when parsing a JWT. The subsequent check for empty
value prevented the error from being exposed. This fix corrects
the equality condition.
The Set() method for nbf has also been corrected to round the
time.Time argument to the nearest second to match the granulity
of the time format string in the JWT JSON. This rounding allows
the marshal/unmarshal roundtrip to JSON to be lossless. Without
it the unit test comparison fails because the initial time value
(from time.Now) has a nanoseconds component that gets stripped
off and lost when encoding to JSON. The time value is also converted
to …
> Fix JWT parsing of JWT NotBefore (nbf) header parameter.

- jwk/jwk.go
- jwk/jwk_test.go
Since failed to parse of key_ops header, it has been fixed.
> Fix constructEssentialHeader: key_ops

- jws/jws.go
- jws/jws_test.go
- jwt/jwt_test.go
The decoding of compact form JWS tokens incorrectly performs a
TrimRight to strip trailing zero bytes from the token signature
after decoding from base64. It should not do this.
I found that about 1% of the JWS tokens we generated using
another tool were failing signature verification by go-jwx.
These JWS tokens were valid and correctly formatted and after
some spelunking into the go-jwx code we discovered this trim
of trailing zeroes from the compact signature was the problem.
This specifically fails when the generated signature (ECDSA
P-384 in this case) actually had a trailing zero byte in the
serialized S component of the signature.
This patch removes the offending TrimRight. A unit test has
also been added to verify one of the specific instances of
a failing JWS token from my …
> Fix bad trimming of compact JWS signatures.

- jwe/aescbc/aescbc.go
- jwe/cipher.go
- jwe/content_crypt.go
- jwe/encrypt.go
- jwe/jwe.go
- jwe/jwe_test.go
- jwe/key_encrypt.go
@Warashi has notified me that using `jwa.A256KW` and `jwa.A256CBC_HS512` together doesn't work. In fact, any of `jwa.A128KW`, `jwa.A192KW`, `jwa.A256KW` doesn't work with content encryption algorithms with key sizes not in the set 16, 24, or 32.
This PR makes changes to properly report that error.
> Properly error out when certain KeyWrap / ContentEncrypt algorithms are used together

- jwt/jwt_test.go
ふと思い立って TestClaimSet 内の (*ClaimSet).Set が返している error をチェックするようにしたらテストが落ちるようになりました。
テストと実装のどちらが間違いなのかわかりませんがとりあえず落ちる状態でPR出しておきます。
> added error check in TestClaimSet

- jwt/verify.go
Time struct derived from deserialised json epoch is in UTC, time.Now() is local time.
> Avoid comparing time structs directly because the time zone may be different

- jwt/jwt_test.go
- jwt/verify.go
> Work with iat == now (truncated down to second)

- jwt/jwt_test.go
- jwt/verify.go
Verify() truncates the time in the `iat` field and Now() to the nearest second when comparing so the `iat` claim fails because Now() is not after `iat` when checking the validity of the token within the same second.
> Add test case for #37: new tokens are invalid in the second they are created

- jws/sign/ecdsa.go
This fix #52 
The problem is dst of copy is larger size than src.
This PR adjusts dst size to fit with src.
> copy only lower bits in ecdsaSignFunc

- jwe/jwe.go
- jwe/jwe_test.go
When using `ECDH_ES_A256KW` to encrypt plaintext, error `invalid key size 64` will be thrown.
In jwe.Encrypt(), content key size in switch case `jwa.ECDH_ES_A256KW`, `jwa.ECDH_ES_A192KW`, `jwa.ECDH_ES_A128KW` is wrong.
```golang
case jwa.ECDH_ES_A128KW, jwa.ECDH_ES_A192KW, jwa.ECDH_ES_A256KW:
pubkey, ok := key.(*ecdsa.PublicKey)
if !ok {
return nil, errors.New("invalid key: *ecdsa.PublicKey required")
}
keyenc, err = NewEcdhesKeyWrapEncrypt(keyalg, pubkey)
if err != nil {
return nil, errors.Wrap(err, "failed to create ECDHS key wrap encrypter")
}
keysize = contentcrypt.KeySize() // content key size is wrong
}
```
Key size divided by 2.
> Thanks my colleague @crownych, he found this bug.
> Fix wrong key size of ECDH-ES + AES key wrap

- .gitignore
- buffer/buffer.go
- jws/jws.go
- jws/jws_test.go
fixes #62
Added idea folders to gitignore
This PR adds a new function that serializes protected headers "as is", without formatting  or removing whitespace.
> jws.Sign() removes whitespace and newlines from JSON

- jws/option.go
git blame / git log tells us that they had their use way back when, but not anymore
refs #79
> Remove unused options

- .gitignore
- jwt/date.go
- jwt/date_test.go
- jwt/example_test.go
- jwt/interface.go
- jwt/internal/cmd/gentoken/main.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/string.go
- jwt/string_test.go
- jwt/token_gen.go
- jwt/token_gen_test.go
- jwt/verify.go
- jwt/verify_test.go
- jwx_example_test.go
fixes #85
1 - Overall Changes
- Removed Token Top Level (Un)Marshal and added JSON Tags for everything
- This simplified code and increased coverage
- Added specific (un)Marshal for NumericDate so that we always return a
number according to the definition of NumericDate on
https://tools.ietf.org/html/rfc7519#page-6
2 - Token Behavior
- We should only accept audience(aud) claims as an array, even if it
is an array of one element. This greatly simplifies code and coverage
3 - Bugs
- If we add private claims, we need to indicate as such when getting
tokens. See example_test.go. We get this for free by using JSON tags
for (un)Marshal.
- When creating a JWT the New() function should behave just
like "var token Token". the New() function was creating an empty
private PrivateClaims map and that …
> Low coverage and unused functions in token_gen.go

- jwt/jwt_test.go
- jwt/string.go
`{"aud": "foo"}` is accepted and converted to `{"aud": ["foo"]}`
TODO: ponder about normalizing marshal'ed output to be single string when StringList length == 1
> Allow StringList values to be flattened when accepting as JSON

- jws/jws.go
- jws/jws_test.go
jws.SplitCompact was not working for JWTs > 4kB.
This PR fixes #61.
> Fix signature verification

- jwt/verify.go
- jwt/verify_test.go
WithClaimValue allows you to verify any claim.
before
```go
if err := token.Verify(
jwt.WithClock(clock),
jwt.WithIssuer("https://accounts.google.com"),
jwt.WithAudience(audience),
); err != nil {
return xerrors.Errorf(": %w", err)
}
if emailVerified, ok := token.Get("email_verified"); !ok || emailVerified != true {
return xerrors.Errorf("token not valid: email is not verified")
}
if email, ok := token.Get("email"); !ok || email != "email@example.com" {
return xerrors.Errorf("token not valid: no permission %v", email)
}
```
after
```go
if err := token.Verify(
jwt.WithClock(clock),
jwt.WithIssuer("https://accounts.google.com"),
jwt.WithAudience(audience),
jwt.WithClaimValue("email_verified", true),
jwt.WithClaimValue("email", "email@example.com"),
); err != nil {
return xerrors.Errorf(": …
```
> Add WithClaimValue to JWT Verify options

- jws/headers.go
- jws/headers_test.go
- jws/internal/cmd/genheader/main.go
The datatype of the "jwk" field of JWS' currently incorrectly specified as jwk.Set. According to the spec this should be a plain JWK, rather than a set (https://tools.ietf.org/html/rfc7515#section-4.1.3).
This bug breaks compatibility with other JWS libraries.
> Fixed data type of JWS["jwk"] to be JWK instead of JWKSet

- jwk/jwk.go
- jwk/option.go
- jws/jws.go
We can use `http.NewRequestWithContext` but it can use from Go 1.13.
I don't use it this PR.
```go
req, err := http.NewRequest(http.MethodGet, jwkurl, nil)
if err != nil {
return nil, errors.Wrap(err, "failed to new request to remote JWK")
}
req.WithContext(ctx)
```
from Go 1.13
```go
req, err := http.NewRequestWithContext(http.MethodGet, jwkurl, nil)
if err != nil {
return nil, errors.Wrap(err, "failed to new request to remote JWK")
}
```
`http.NewRequestWithContext` has performace advantage. `req.WithContext(ctx)`copy http.Request.
```go
func (r *Request) WithContext(ctx context.Context) *Request {
if ctx == nil {
panic("nil context")
}
r2 := new(Request)
*r2 = *r //--------------------------------- copy http.Request  -------------------------------
r2.ctx = ctx
r2.URL = cloneURL(r.URL) …
```
> Pass context to fetch functions

- jwk/jwk.go
I'm sorry that I have to pass return value from WithContext to Do method.
#144
Thanks @zchee
https://github.com/lestrrat-go/jwx/commit/0363a73b1277f4f9c48b6ebc531f2bce0a6f4f25#r38431948
> Fix Pass context to fetch functions #144

- .travis.yml
- internal/iter/mapiter.go
- jws/headers.go
- jws/headers_gen.go
- jws/headers_test.go
- jws/interface.go
- jws/internal/cmd/genheader/main.go
- jws/jws.go
- jws/jws_test.go
- jws/message.go
- jws/signature.go
- jws/signer_test.go
- jwt/interface.go
- jwt/jwt.go
- jwt/token.go
- jwt/token_test.go
fixes #149
* API to iterate all headers pairs in a header
* API to access common headers (e.g. `h.Algorithm()`, `h.KeyID()`, etc.)
* Public fields have all been changed to private fields
* Types which didn't need to be public have been either removed or unexported
* `jws.Header` is now an interface. `jws.StandardHeader` no longer exists
* `jwt` Iterator API has been changed to conform with the new API for `jws`
> Refactor JWS API

- jwt/jwt.go
- jwt/jwt_test.go
- jwt/options.go
I believe it's standard practice that if a JWKS only contains a single key then the kid isn't necessarily required in the JWT header. The validation code can assume it should use the only available key.
However, I haven't read the spec so if this is not the case then please disregard this PR and I'll continue to use my fork.
To keep the API the same and not change existing behaviour I added a new option for jwt.Parse to allow this behaviour.
- If the useDefault flag is true and there's a single key in the set it'll use that to verify the token.
- If the useDefault flag is true and there's multiple keys in the set it'll error.
- If the useDefault flag is false then the behaviour is unchanged.
I wasn't sure on naming, **_With..._** didn't seem to fit the use case here, so I went with …
> Allow jwt.Parse using JWKS to use default single key when no kid in JWT header

- jws/jws.go
Fix for #238.
`jws.Message` object is for inspecting JOSE headers and signatures in a JWS message (in receiver usecases). It's not meant to be passed to `Verify` method of `Verifier`.
> jws: fix document on Verify method

- internal/base64/base64.go
- internal/base64/base64_test.go
- jwk/x5c_test.go
Fixes https://github.com/lestrrat-go/jwx/issues/243
> Encode x5c field as base64 with padding to conform with JWK and JWS RFCs

- .github/workflows/ci.yml
The tip strategy was removed a while back. Update codecov to upload for the 1.15 go version.
Not 100% sure on how the codecov upload works, so just guessing here... should it somehow be disabled for PRs?
> Reinstate codecov uploads

- jwt/internal/cmd/gentoken/main.go
- jwt/openid/token_gen.go
- jwt/token_gen.go
Noticed when running staticcheck over the repository.
> jwt: remove unused writeJSON function, fix typo in error

- jwe/headers_gen.go
- jwe/internal/cmd/genheader/main.go
- jws/headers_gen.go
- jws/internal/cmd/genheader/main.go
- jwt/internal/cmd/gentoken/main.go
- jwt/openid/token_gen.go
- jwt/token_gen.go
The only semi-serious one is making the MarshalJSON receiver a pointer
due to the mutex lock.
> remove unused json tags, fix other go vet complaints

- jwt/jwt.go
The function `jwt.WithVerifyKeySet(jwk.Set)` doesn't exists anymore in `jwt` package. Updated godoc with the new function name `jwt.WithKeySet(*jwk.Set)`.
> Updated name of KeySet Option in godoc

- go.mod
- internal/concatkdf/concatkdf.go
- internal/jose/jose.go
- internal/jwxtest/jwxtest.go
- jwe/decrypt.go
- jwe/encrypt.go
- jwe/internal/aescbc/aescbc.go
- jwe/internal/cipher/cipher.go
- jwe/internal/content_crypt/content_crypt.go
- jwe/internal/keyenc/keyenc.go
- jwe/jwe.go
- jwe/message.go
pdebug had a problem with race conditions. It's a print debug tool, so who cares if it's buggy, but yeah, testing with `-race` (and more parallelization in tests) ended up in errors, so ...
> Switch to pdebug v3

- Makefile
As examples is now a standalone "module" with its own go.mod,
go test ./... will happily ignore tests in that directory,
as they are considered "outside" of jwx.
This change adds an explicit test run for examples directory
> Add explicit tests for examples/ directory

- Makefile
- cmd/jwx/jwx.go
- examples/jwk_example_test.go
- examples/jwt_benchmark_test.go
- examples/jwt_example_test.go
- jwe/jwe.go
- jwk/jwk.go
- jwk/jwk_test.go
- jwk/refresh.go
- jws/jws.go
- jws/jws_test.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/openid/openid_test.go
- jwt/validate_test.go
> v1.1.0: Standardize on Parse([]byte), ParseString(string), and ParseReader(io.Reader)

- internal/fs/fs.go
- jwk/fs_test.go
https://github.com/golang/go/issues/43980
go1.16 probably won't allow us to use go:embed, so just implement
an in memory FS
> Use fs.InMmeory instead of go:embed

- internal/json/registry.go
- jwe/encrypt.go
- jwe/headers_gen.go
- jwe/interface.go
- jwe/internal/cmd/genheader/main.go
- jwe/jwe.go
- jwe/jwe_test.go
- jwe/options.go
- jwk/ecdsa_gen.go
- jwk/internal/cmd/genheader/main.go
- jwk/jwk.go
- jwk/jwk_test.go
- jwk/okp_gen.go
- jwk/rsa_gen.go
- jwk/symmetric_gen.go
- jws/headers_gen.go
- jws/internal/cmd/genheader/main.go
- jws/jws.go
- jws/jws_test.go
- jwt/internal/cmd/gentoken/main.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/openid/openid.go
- jwt/openid/token_gen.go
- jwt/token_gen.go
fixes #332
Each message in the `jwe`, `jwk`, `jws`, `jwt` protocols have predefined fields. Any other field which is not defined in the spec can be populated by the user. Howeversince we don't know the type information before hand we could not decode these values into Go objects.
This PR fixes this by creating a global registry of key names to their types. For example, this makes it so that when you either use `jwt.Parse` or `json.Unmarshal`, the value pointed by x-foo-bar is marshaled into `myawesomepkg.Object`.
```go
func init() {
jwt.RegisterCustomField(`x-foo-bar`, myawesomepkg.Object{})
}
```
This has global effects.
It is the caller's responsibility to implement the proper `json.Unmarshaler` methods for custom unmarshaling.
> Implement Custom Fields

- README.md
The main readme was missed earlier.
> readme: update tables for secp256k1/ES256K, fix typo

- cmd/jwx/README.md
I can't actually run the tool due to the go 1.16 requirement, but pretty sure these are right.
> cmd/jwx: fix readme typos

- Changes
- bench/go.sum
- examples/go.sum
- go.mod
- go.sum
should fix compilation being killed by OOM on environments with less memory (only applicable if you use `-tags jwx_goccy`
> Update goccy/go-json to v0.4.7

- .github/workflows/ci.yml
- .github/workflows/smoke.yml
- Changes
- Makefile
- README.md
- cmd/jwx/go.mod
- cmd/jwx/go.sum
- cmd/jwx/jwk.go
- internal/ecutil/ecutil.go
- internal/jwxtest/jwxtest.go
- jwa/compression_gen.go
- jwa/content_encryption_gen.go
- jwa/elliptic_gen.go
- jwa/elliptic_gen_test.go
- jwa/internal/cmd/gentypes/main.go
- jwa/key_encryption_gen.go
- jwa/key_type_gen.go
- jwa/secp2561k.go
- jwa/secp2561k_test.go
- jwa/signature_gen.go
- jwk/ecdsa.go
- jwk/es256k.go
- jwk/es256k_test.go
- jwk/jwk_test.go
- jws/jws_test.go
- jws/secp256k1_test.go
- jwx_test.go
Per #345 by default we're going to skip compiling in ES256K.
We WILL NOT be using `database/sql` style explicit importing scheme for the time being. If we do, this will be done in the next API breaking release. Instead we will just toggle these "extra" features using build tags like `jwx_goccy`. For this one we will be using `jwx_es256k`
> Toggle ES256K using a build tag

- Changes
- README.md
- go.mod
- jwt/README.md
- jwt/http.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/options.go
> Add utilities to parse JWTs stored in http.Request, http.Header, or url.Values

- jwt/jwt.go
- jwt/jwt_test.go
`jwt.Sign` function automatically sets `"JWT"` to `typ` JOSE header parameter. Even though the user provides a custom value for `typ` using `WithHeaders` option, it's overwritten by `"JWT"`.
This pull-request changes the above behavior. Now `jwt.Sign` sets `"JWT"` to `typ` only if the user doesn't provide a custom value for it.
Tests are added to jwt_test.go
> jwt: allow setting a custom value to "typ" JOSE header parameter

- .github/workflows/ci.yml
- .github/workflows/smoke.yml
- bench/go.sum
- examples/go.sum
- go.mod
- go.sum
Should fix cases where calling `AsMap()` would panic when there are null values.
> Update github.com/lestrrat-go/iter dependency to v1.0.1

- jwk/jwk_test.go
- jwk/rsa.go
Hi,
we upgraded to 1.6.2 and now getting an panic error in our unit tests while creating a new `jwk.Key` from an empty rsa private or public key:
```
Test Panicked
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212
Full Stack Trace
math/big.(*Int).Bytes(...)
github.com/lestrrat-go/jwx/jwk.(*rsaPublicKey).FromRaw(0xc0002fed00, 0xc0003ec1d0, 0x0, 0x0)
github.com/lestrrat-go/jwx/jwk.New(0xa6fd60, 0xc0003ec070, 0x0, 0x0, 0xc0000f6fb0, 0x1)
....
```
So I added a validatation that at least an error is thrown.
> jwk: "invalid memory address or nil pointer dereference" error when create new jwk.Key from empty RSA private  key

- README.md
This PR updates the `github.com/coreos/go-oidc` library to the updated repository link and uses the redirected docs link for `golang.org/x/oauth2`.
> docs: fix outdated links for related libraries

- jwt/http.go
This PR changes the package in the examples for `ParseRequest` from `jwthttp` to `jwt`.
Not sure if using `jwthttp` is intended or not but I think that it will be clearer to users if we change this since they belong in the `jwt` package.
> docs: align package name in ParseRequest examples

- Changes
- Makefile
- examples/jwt_example_test.go
- internal/json/json.go
- jwt/internal/cmd/gentoken/main.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/openid/token_gen.go
- jwt/options.go
- jwt/token_gen.go
I have been informed that apparently AWS Cognito doesn't play well when the "aud" claim of a JWT is in the array-of-strings format.
This PR adds the optional ability to change the behavior of JWT serialization such that when you only have a single "aud" claim, the field is rendered as a string.
So where previously it would have rendered as follows:
```json
{ "aud": ["foo"] }
```
Now it is possible to have it serialized as:
```json
{ "aud": "foo" }
```
This behavior is turned on by opting in, and you need to explicitly call a method that triggers a global effect:
```go
jwt.Settings(jwt.WithFlattenAudience(true))
```
> Add way to serialize JWT "aud" claim into a single string token

- Changes
- internal/json/json.go
- jwk/ecdsa_gen.go
- jwk/interface.go
- jwk/internal/cmd/genheader/main.go
- jwk/jwk.go
- jwk/jwk_test.go
- jwk/okp_gen.go
- jwk/option.go
- jwk/rsa_gen.go
- jwk/set.go
- jwk/symmetric_gen.go
- jwt/interface.go
- jwt/internal/cmd/gentoken/main.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/openid/interface.go
- jwt/openid/token_gen.go
- jwt/options.go
- jwt/token_gen.go
fixes #384 
I'm still a bit weary of this feature, but perhaps this is the only solution to a problem described in the above issue.
This PR allows something like this:
```go
type Foo struct {
....
}
token, _ := jwt.Parse(..., jwt.WithTypedClaim("foo", Foo{}))
token.Get("foo") // returns an instance of Foo. otherwise something like a map[string]interface{} is returned
```
> Implement per-object custom typed fields

- docs/04-jwk.md
I think this was a typo - updated `.Configure` to `.Fetch` in this guide.
> Fix typo in docs 04-jkw.md

- jwt/jwt.go
Not sure if this is the only typo, but this stands out to me in my error messages and would be nice to fix.
> fix typo for error message if signature is invalid

- examples/jwt_example_test.go
- jwt/README.md
- jwt/openid/openid.go
This PR replaces examples and documentation strings using jwt.WithOpenIDClaims() with jwt.WithToken(openid.New().
> Fix documentation and examples for OpenID claims

- Changes
- jws/jws.go
- jws/jws_test.go
- jws/option.go
This makes jws symmetrical in terms of being able to obtain the raw content and the Message object
> Implement WithMessage option for jws

- Changes
- jwk/interface.go
- jwk/jwk_test.go
- jwk/set.go
> (jwk.Set).Clone, more robust test, fix another off by one

- jwt/validate.go
- jwt/validate_test.go
If you have a `0` as a token expiration, issued at, or not before claim, validation will fail.  Currently you have to set it to be -62135596800 to pass the `time.IsZero()` check, this pull would allow unix time 0 to pass.
> Allows 0 to be valid token expiration instead of -62135596800

- Changes
- jwk/interface.go
- jwk/refresh.go
- jwk/refresh_test.go
> Implement ErrorSink method

- jwk/refresh.go
- jwt/jwt_test.go
- jwt/serialize.go
> Rfc7797 prohibit in jwt

- jwe/headers.go
- jwe/headers_gen.go
- jwe/internal/cmd/genheader/main.go
- jwk/ecdsa.go
- jwk/ecdsa_gen.go
- jwk/interface_gen.go
- jwk/internal/cmd/genheader/main.go
- jwk/jwk.go
- jwk/okp.go
- jwk/okp_gen.go
- jwk/rsa.go
- jwk/rsa_gen.go
- jwk/set.go
- jwk/symmetric.go
- jwk/symmetric_gen.go
- jws/headers.go
- jws/jws.go
- jwt/jwt.go
- jwt/openid/openid.go
Iteration of lestrrat-go/iter using goroutine and channel is sometimes useful with a generic interface, but it can be slow.
I tried the benchmark for `LookupKey`, it has been improved.
```go
package jwk_test
import (
"context"
"testing"
"github.com/lestrrat-go/jwx/jwk"
)
const u = "https://www.googleapis.com/oauth2/v3/certs"
func BenchmarkVerifySet(b *testing.B) {
ctx := context.Background()
ar := jwk.NewAutoRefresh(ctx)
ar.Configure(u)
set, err := ar.Fetch(ctx, u)
if err != nil {
b.Fatal(err)
}
b.ResetTimer()
for i := 0; i < b.N; i++ {
_, ok := set.LookupKeyID("REPLACE_THE_REAL_KEY_ID")
if !ok {
b.Fatal("no key")
}
}
}
```
before
```
goos: linux
goarch: amd64
pkg: github.com/lestrrat-go/jwx/jwk
cpu: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
BenchmarkVerifySet-4   	 1214281 …
```
> Optimize iteration

- Changes
- docs/01-jwt.md
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/options.go
This also fixes a subtle asymmetry in how single key versus a key set
is used. This change should now fix this, as well as allow dynamic
selection of key sets to use via the KeySetProvider
> Add KeySetProvider

- Changes
- jwt/jwt.go
- jwt/jwt_test.go
if the payload passed to `jwt.Parse` is a JSON object *looks* like JWT, e.g. has an `"aud"` field, but otherwise has fields that does not verify, e.g. `"exp"` is invalid, the current code silently bypasses verification.
> Fix verification bypass when passed a raw JSON object with specific attributes

- jwt/jwt.go
- jwt/jwt_test.go
There's no issue in practice, I think, but it's silly to loop over the keys when we've already selected the key up front...
`jws.verifyCompact` looks like it makes sure that the kid's match, but it's a bit unnecessary to rely on that here.
> jwt: only infer algorithm on the already-selected key

- Changes
- docs/02-jws.md
- jws/interface.go
- jws/jws.go
- jws/jws_test.go
- jws/message.go
- jws/option.go
> Fix jws.Sign() to allow detached, unencoded payload

- jwk/interface_gen.go
- jwk/internal/cmd/genheader/main.go
I suspect that the user could not find the relationship between the JSON field name and the corresponding jwk.Key method name in #565
This PR adds some rudimentary documentation to address this.
> Generate rudimentary comments for Key interface

- docs/04-jwk.md
- docs/99-faq.md
References to `Parse a key or set in PEM format` are broken.  This is a minor fix for that.
> Fix link to parse-a-key-or-a-set-in-pem-format

- Changes.v2
- examples/jwt_example_test.go
- examples/jwt_parse_example_test.go
- examples/jwt_parse_request_example_test.go
- examples/jwt_parse_with_key_example_test.go
- examples/jwt_readfile_example_test.go
- examples/jwt_validate_detect_error_type_example_test.go
- examples/jwt_validate_example_test.go
- examples/jwx_example_test.go
- examples/jwx_readme_example_test.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/openid/openid_test.go
- jwt/options.yaml
- jwt/options_gen.go
- jwt/options_gen_test.go
- jwt/token_test.go
- jwt/validate_test.go
jwt.Parse no longer allows unverified and/or unvalidated tokens to be obtained by the caller by default. Allowing this had significant security problems.
Now you need to explicitly ask for it to be disabked to get the original behavior
> Enable validate verify by default

- jws/jws.go
- jws/jws_test.go
> Fix jws.Verify not respecting the b64 header in the protected headers

- jwt/jwt_test.go
- jwt/validate.go
Fixes #719: I simply added a new case to detect whether the target error is an instance of `missingRequiredClaimError` and changed the test to avoid a regression in the future
> Fix `jwt.isValidationError()` false negative for `ErrMissingRequiredClaim`

- jwt/validate.go
* Deprecate ErrMissingRequireClaim
* Provide alternative ErrRequiredClaim
* Clearly document that error values returned by ErrXXX should only be
used for errors.Is comparison
* Clearly document that ErrMissingRequiredClaim should not be used
> Tweak error JWT namings

- jwt/internal/types/date.go
- jwt/jwt.go
- jwt/openid/openid_test.go
- jwt/options.yaml
- jwt/options_gen.go
- jwt/options_gen_test.go
> Allow escape hatch for those who (incorrectly) use RFC3339 in Numeric Date fields

- Changes
- jws/jws_test.go
- jws/key_provider.go
- jws/options.go
- jws/options.yaml
- jws/options_gen.go
- jws/options_gen_test.go
- tools/cmd/genoptions/main.go
Builds on top of #757 
* Refactor and add tests
* Refactor code
* Add `WithMultipleKeysPerKeyID` to preserve old behavior
I think the last bit is necessary because we should keep new behavior opt-in as much as possible so that people upgrading do not get surprised.
> Accept multiple keys given a key ID

- formatkind_string_gen.go
- jwk/interface_gen.go
- tools/cmd/genjwk/main.go
I rather suspect KeyType() returns the `kty` rather than the `kid`.
> fix doc bug in Key interface

- Changes
- docs/03-jwe.md
- jwe/internal/keyenc/interface.go
- jwe/internal/keyenc/keyenc.go
- jwe/internal/keygen/interface.go
- jwe/internal/keygen/keygen.go
- jwe/jwe.go
- jwe/jwe_test.go
fixes #803
* Add tests
* Add notes in the docs that apu/apv should be passed using
`jwe.WithPerRecipientHeaders()` option along with the key
* Fix an omission where header values for apu/apv were not
properly passed when encrypting
> [jwe] Fix jwe encryption around apu/apv

- jws/interface.go
fixes a typo in the interface.go file with the Signer interface.
> fix typo: scond -> second

- jwe/internal/keygen/keygen.go
- jwe/jwe_test.go
- jws/ecdsa.go
- jws/jws_test.go
> Protect jws.Verify() and jwe.Encrypt() from panic on go1.19+

- jwe/io.go
- jwk/io.go
- jws/io.go
- jwt/io.go
- tools/cmd/genreadfile/main.go
`var readFileOptions []ReadFileOption` are never used. （something mistake?）
Generate `var parseOptions []ParseOption` only when needs.
> Remove unused variables in ReadFile

- .github/workflows/ci.yml
- Changes
- jwa/compression_gen.go
- jwa/content_encryption_gen.go
- jwa/elliptic_gen.go
- jwa/key_encryption_gen.go
- jwa/key_type_gen.go
- jwa/signature_gen.go
- jws/jws_test.go
- jws/signer.go
- jws/verifier.go
- tools/cmd/genjwa/main.go
> Hook in jwa.RegisterXXX functions with jws.Register(Signer|Verifier)

- Changes
- jwe/decrypt.go
- jwe/interface.go
- jwe/internal/keyenc/interface.go
- jwe/internal/keyenc/keyenc.go
- jwe/internal/keygen/interface.go
- jwe/internal/keygen/keygen.go
- jwe/jwe.go
- jwe/jwe_test.go
This allows users to specify a key who can encrypt/decrypt by itself, much like the built-in crypto.Signer interface.
> Implement jwe.KeyEncrypter and jwe.KeyDecrypter

- jwe/internal/aescbc/aescbc.go
godoc says hash.Hash.Write never returns an error: https://pkg.go.dev/hash#Hash
> Write (via the embedded io.Writer interface) adds more data to the running hash.
> It never returns an error.
So, we don't need to check errors of Write and panics in Hmac.ComputeAuthTag.
> remove unnecessarily err checks

- jwk/okp.go
To avoid this panic: https://github.com/golang/go/blob/3adcce5ae7203e9ee7bee93a4ad913a3145e682e/src/crypto/ed25519/ed25519.go#L168
> add size check

- Changes
- jws/ecdsa.go
- jws/eddsa.go
- jws/jws.go
- jws/options.go
- jws/rsa.go
- jwt/options.go
- jwx_test.go
> jws: Check key types for those that implement crypto.Signer

- Changes
- jwt/jwt.go
- jwt/jwt_test.go
> Fix ParseInsecure to parse the token even when a key is given

- Changes
- jws/jws.go
- jws/jws_test.go
> Add jws.IsVerificationError

- cmd/jwx/jwk.go
`io.Reader.Read` docs say the following: 
```
If some data is available but not len(p) bytes, Read conventionally returns what is available instead of waiting for more.
```
We need to use `io.ReadFull` or `rand.Read` (which in turn calls `ReadFull`) to ensure that we fill the entire buffer.
> Use io.ReadFull to ensure that generated jwk match the expected keysize

- Changes
- jws/jws.go
- jws/jws_test.go
- jws/options.go
- jws/options.yaml
- jws/options_gen.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/options.yaml
- jwt/options_gen.go
- jwt/options_gen_test.go
Solution #1077 for v2
Adds the ability to control which serialization formats are accepted in `jws.Parse` and `jws.Verify`, and further adds `jwt.WithCompactOnly(bool)` to the global settings to disallow parsing of JSON formats.
This makes jwx better adhere to the RFC while keeping backwards compatibility.
> [v2] jws: allow specifing parse format/jwt: disallow JSON

- Changes
- jwt/jwt_test.go
- jwt/options.yaml
- jwt/options_gen.go
- jwt/options_gen_test.go
- jwt/validate.go
```go
// does NOT check for iat, exp, and nbf, but checks for iss
jwt.Validate(token, jwt.WithResetValidators(true), jwt.WithIssuer("foo"))
```
> Allow resetting the default jwt validators

- Changes
- internal/json/goccy.go
- internal/json/json.go
- internal/json/stdlib.go
- jwe/jwe.go
- jwx_test.go
* Fix #1140 by changing code depending on the value of useNumber settings
* Change internal representation of useNumber to atomic operation.
> Fix conversion in JWE when WithUseNumber global settings is used (#1140)

- internal/jwxtest/jwxtest.go
- jwa/key_encryption_gen.go
- jwa/key_encryption_gen_test.go
- jwe/decrypt.go
- jwe/internal/keyenc/keyenc.go
- jwe/jwe.go
- jwx_test.go
- tools/cmd/genjwa/main.go
This pull request would add support for the `RSA-OAEP-384` and `RSA-OAEP-512` key encryption algorithms. I think this is just a minor change as the base algorithms `RSA-OAEP` and `RSA-OAEP-256` are already implemented. The only difference these new algorithms have is that they use a different hashing algorithm `SHA384` and `SHA512` respectively instead of `SHA1` or `SHA256`.
The hashing algorithms `SHA384`and `SHA512` are already used in different algorithms, so these are not new. The only thing I wasn't sure about it how the following case should be handled:
[permalink](https://github.com/Hannes-Kunnen/jwx/blob/458bea5fa7a67cc251703d04654eb93f8df2bb9f/jwe/internal/keyenc/keyenc.go#L458-L477)
```go
func (e RSAOAEPEncrypt) EncryptKey(cek []byte) (keygen.ByteSource, error) {
var hash …
```
> Add support for RSA-OAEP-384 and RSA-OAEP-512

- cmd/jwx/jws.go
- jws/options.go
- jwt/jwt.go
The option never worked since v2, but it was kept around, and the documentation sometimes refered to this option, which it shouldn't have.
fixes #1153
> Deprecate jws.WithHeaders

- jwt/README.md
This is in the `openid` subdirectory inside the `jwt` directory, but this file is already inside the latter.
> Fix link to openid
