lestrrat-go/jwx

jws/jws.go

Revert "accept "sig" use of JWK for verifying"

---

jws/interface.go
jws/jws.go
jws/jws_test.go

Implement JWKAcceptor

---

internal/emap/emap.go
jwk/jwk.go
jwk/jwk_test.go

Fixed an issue that could not get the value of the x5c in parsed jwk.
example:
```go
package main
import (
"fmt"
"github.com/lestrrat/go-jwx/jwk"
)
func main() {
set, _ := jwk.ParseString(RawJWKJSON())
key := set.Keys[0].(*jwk.RsaPublicKey)
fmt.Printf("x5c = %#v", key.X509CertChain)
}
func RawJWKJSON() string {
return `{"keys":[{
"kty":"RSA",
"use":"sig",
"kid":"1b94c",
"n":"vrjOfz9Ccdgx5nQudyhdoR17V-IubWMeOZCwX_jj0hgAsz2J_pqYW08PLbK_PdiVGKPrqzmDIsLI7sA25VEnHU1uCLNwBuUiCO11_-7dYbsr4iJmG0Qu2j8DsVyT1azpJC_NG84Ty5KKthuCaPod7iI7w0LK9orSMhBEwwZDCxTWq4aYWAchc8t-emd9qOvWtVMDC2BXksRngh6X5bUYLy6AyHKvj-nUy1wgzjYQDwHMTplCoLtU-o-8SNnZ1tmRoGE9uJkBLdh5gFENabWnU5m1ZqZPdwS-qo-meMvVfJb6jJVWRpl2SUtCnYG2C32qvbWbjZ_jBPD5eunqsIo1vQ",
"e":"AQAB",
"x5c": …
```

Fix: emap.GetStringSlice for jwk.x5c

---

README.md

Fixes two spelling errors in the README.md file.

Fix spelling issues in README.md

---

jwt/jwt_test.go
jwt/verify.go

add checks for iat and jti
refs #10

check for jti and iat

---

jwe/jwe_test.go

うまく動かないケースがあったのでテストにしました
他の組み合わせでも動かないケースがあるかもしれませんが、組み合わせが多くて全てテストにするのは大変だったのでとりあえず動かないことを確認したケースのみテストにしました。

added test about A256KW and A256CBC_HS512

---

jwt/jwt_test.go

goes to show that you really should be checking for errors. silly me.

Fix JWT tests

---

jwt/README.md
jwt/example_test.go
jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

Make sure jwt.Parse can use jws.Verify if given parameters

---

jws/jws.go
jwt/README.md
jwt/example_test.go
jwt/jwt.go
jwt/jwt_test.go

Thought about having a global flab, but on second thought, just created a separate API.
fixes #38

Parse and verify

---

jwk/jwk.go
jwk/jwk_test.go

Implement Set.UnmarshalJSON

---

internal/emap/emap.go
jwe/encrypt.go
jwe/interface.go
jwe/jwe.go
jwe/key_encrypt.go
jws/verify/ecdsa.go

Many thanks for this package! Just caught a couple more typo nitpicks.

cosmetic: fix whitespace and error message typos

---

jws/jws_test.go
jws/sign/ecdsa.go
jws/verify/ecdsa.go

fixes #63 
P-521 (ES512) and possibly others do not have such constraint

Curve bits do not need to be a multiple of Keysize

---

.travis.yml
jwk/jwk.go
jwk/jwk_test.go
jwk/option.go

Allow specifying the HTTP Client for jwk.Fetch

---

jwk/jwk.go
jws/jws_test.go

Repenno 72

---

jws/headers_test.go

fixes #75
Increasing coverage to ~50%

Increase JWS Header coverage

---

jws/headers.go
jws/internal/cmd/genheader/main.go
jws/jws.go
jws/jws_test.go

fixes #77
- Please see issue for problem description
- message.go coverage is now ~100%

Incorrect Parsing of Complete JWS JSON

---

jwe/interface.go

Remove unused fields found by `unused` tool

---

Makefile
jws/jws.go
jwt/date.go
jwt/internal/cmd/gentoken/main.go
jwt/jwt_test.go
jwt/string.go
jwt/token_gen.go

Coverage work on `aud` key and date keys

---

jwk/symmetric.go

Remove unused SymmetricKey.UnmarshalJSON

---

jwk/headers_gen.go
jwk/headers_test.go
jwk/internal/cmd/genheader/main.go

fixes #92
- Coverage at ~ 80%
- Cleanup

Low coverage and unused functions in jwk/headers_gen.go

---

jwt/date.go
jwt/jwt_test.go

Test NumericDate.Accept

---

cmd/jwx/jwx.go
jws/headers.go
jws/headers_test.go
jws/internal/cmd/genheader/main.go
jws/jws_test.go
jws/message.go
jws/sign/ecdsa_test.go
jws/sign/hmac.go
jws/sign/hmac_test.go
jws/verify/ecdsa_test.go
jws/verify/hmac.go
jws/verify/hmac_test.go
jws/verify/rsa_test.go

Repenno jwx 89

---

jwt/internal/cmd/gentoken/main.go
jwt/token_gen.go

Remove redandunt use of time conversion methods

---

jwt/internal/cmd/gentoken/main.go
jwt/jwt_test.go
jwt/token_gen.go

more coverage, cosmetic changes

---

internal/rsautil/rsautil.go
internal/rsautil/rsautil_test.go

Bug in rsautil.go and low coverage

---

jwk/ecdsa.go
jwk/headers_gen.go
jwk/internal/cmd/genheader/main.go
jwk/rsa.go
jwk/symmetric.go
jws/jws.go
jws/jws_test.go

Can we consider removing pdebug dependency?

---

Makefile

fixes #113
- fix filename
- fix coverage report command

Makefile issue

---

jwt/example_test.go
jwt/internal/cmd/gentoken/main.go
jwt/jwt_test.go
jwt/token_gen.go
jwt/token_gen_test.go
jwt/verify.go
jwt/verify_test.go
jwx_example_test.go

Reinstate private claims

---

jwt/date.go
jwt/date_test.go

add tests and clean date.go

---

jwt/internal/cmd/gentoken/main.go
jwt/token_gen.go

They probably used to contain more in a previous version, but not
anymore, so off they go
saw it in #133, porting this part only for this PR

Remove else clauses.

---

internal/base64/base64.go
jwk/jwk_test.go

Work with all base64 encoding patterns

---

jws/headers.go
jws/headers_test.go
jws/internal/cmd/genheader/main.go

Revert "Fixed data type of JWS["jwk"] to be JWK instead of JWKSet"

---

jws/jws.go
jws/jws_test.go

Don't wrap previous errors

---

.gitignore
.travis.yml
go.mod

Add go.mod

---

buffer/buffer.go
internal/ecdsautil/ecdsautil_test.go
internal/rsautil/rsautil_test.go
jwe/interface.go
jwe/internal/cipher/cipher.go
jwk/ecdsa_test.go
jwk/headers_test.go
jwk/interface.go
jws/interface.go
jws/jws_test.go
jwt/jwt_test.go
jwt/token_test.go

I like https://github.com/golangci/golangci-lint
I will add golangci-lint to the CI in other PR if you like it.

Fix golangci-lint warning

---

jwe/headers_gen.go
jwe/internal/cmd/genheader/main.go
jwe/jwe_test.go
jwe/message.go
jws/headers_gen.go
jws/internal/cmd/genheader/main.go

fixes #161
This is a prerequisite for #158

jws header fields as pointers

---

.gitignore
.golangci.yml
internal/concatkdf/concatkdf.go
jwe/encrypt.go
jwe/headers_gen.go
jwe/interface.go
jwe/internal/aescbc/aescbc.go
jwe/internal/aescbc/aescbc_test.go
jwe/internal/cmd/genheader/main.go
jwe/internal/keyenc/keyenc.go
jwe/internal/keygen/keygen.go
jwe/jwe.go
jwe/jwe_test.go
jwk/ecdsa.go
jwk/rsa.go
jws/jws.go
jws/sign/ecdsa.go
jws/sign/hmac.go
jws/sign/rsa.go
jws/verify/ecdsa.go
jws/verify/rsa.go
jwt/openid/address.go

Sonatard fix error

---

Changes
README.md
jws/verify/ecdsa.go
jwt/README.md
jwt/options.go
jwx.go

releng for 1.0.0

---

.github/workflows/ci.yml
Makefile
README.md

I tried to post jwx on awesome-go, awosome-go needed codecove.
If you need not the following Codecov Report, I will add codecov.yml.
```yaml
comment: false
```

Upload coverage file to codecov

---

jwk/ecdsa_gen.go
jwk/ecdsa_test.go
jwk/internal/cmd/genheader/main.go
jwk/rsa_gen.go
jwk/symmetric_gen.go
jwt/internal/cmd/gentoken/main.go

Encode using base64 WITHOUT the "=" padding

---

Changes
internal/base64/base64.go
jwe/compress.go
jwe/encrypt.go
jwe/headers_test.go
jwe/interface.go
jwe/internal/cipher/cipher.go
jwe/internal/cipher/interface.go
jwe/jwe.go
jwe/jwe_test.go
jwe/lowlevel_test.go
jwe/message.go
jwk/certchain.go
jwk/ecdsa_gen.go
jwk/ecdsa_test.go
jwk/internal/cmd/genheader/main.go
jwk/jwk.go
jwk/jwk_test.go
jwk/option.go
jwk/rsa_gen.go
jwk/symmetric_gen.go
jwk/x5c_test.go
jwt/internal/types/date.go
jwt/internal/types/date_test.go
jwt/openid/interface.go
jwt/openid/openid_test.go

Play the coverage game, take 3

---

jwt/jwt.go
jwt/jwt_test.go

Fixes #194 
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

fix bug where invalid algorithm results in nil error response

---

jws/verify/verify.go
jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

Create a way to automatically choose a key to use for JWT verification from a given jwk.Set

---

jwt/jwt.go
jwt/openid/openid_test.go

Make sure to use openid.Token when WithOpenIDClaims() is specified

---

README.md
jwx_example_test.go

Add documentation for #236

---

internal/jose/jose.go
jwe/jwe.go
jwe/jwe_test.go
jwe/message.go
jwx_test.go

Refactor recipient mangling in both JSON/Compact parsing, and use the same code

---

jwk/interface.go

https://github.com/lestrrat-go/jwx/pull/261#discussion_r549520884

Remove  json tag from KeySet

---

go.mod
jwk/interface.go
jwk/option.go
jwk/refresh.go
jwk/refresh_test.go

Implement jwk.AutoRefresh to automatically refresh JWKS in an asynchronous manner

---

jwk/jwk.go
jws/jws.go
jws/jws_test.go
jwt/jwt.go
jwt/jwt_benchmark_test.go

Slight rework of #289 optimize jwt and jws parsing

---

cmd/jwx/jwx.go
examples/jwt_example_test.go
jwe/jwe_test.go
jwk/ecdsa_test.go
jwk/interface.go
jwk/jwk.go
jwk/jwk_test.go
jwk/option.go
jwk/refresh.go
jwk/rsa_test.go
jwk/set.go
jwk/set_test.go
jws/headers_gen.go
jws/headers_test.go
jws/internal/cmd/genheader/main.go
jws/jws.go
jws/jws_test.go
jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

New API for jwk.Set

---

cmd/jwx/jwx.go
examples/jwt_example_test.go
internal/jwxtest/jwxtest.go
jwe/jwe_test.go
jwk/ecdsa.go
jwk/ecdsa_gen.go
jwk/ecdsa_test.go
jwk/interface.go
jwk/internal/cmd/genheader/main.go
jwk/jwk.go
jwk/jwk_test.go
jwk/okp.go
jwk/okp_gen.go
jwk/option.go
jwk/refresh.go
jwk/rsa.go
jwk/rsa_gen.go
jwk/rsa_test.go
jwk/set.go
jwk/set_test.go
jwk/symmetric.go
jws/headers_gen.go
jws/headers_test.go
jws/internal/cmd/genheader/main.go
jws/jws.go
jws/jws_test.go
jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

I made #297 but it was against master. now doing it against develop/v1.1.0
fixes #293

Implement jwk.PublicRawKeyOf(), jwk.PublicKeyOf(), and jwk.PublicSetOf()

---

jwk/interface.go
jwk/jwk.go
jwk/option.go
jwk/refresh.go

refs: https://github.com/lestrrat-go/jwx/pull/306#discussion_r562591768

Use HTTPClient interface instead of raw *http.Client

---

Changes
jwe/compress.go
jwe/message.go
jwk/ecdsa.go
jwk/ecdsa_gen.go
jwk/ecdsa_test.go
jwk/interface_gen.go
jwk/internal/cmd/genheader/main.go
jwk/okp.go
jwk/okp_gen.go
jwk/rsa.go
jwk/rsa_gen.go
jwk/rsa_test.go
jwk/set.go
jwk/symmetric.go
jwk/symmetric_gen.go

Also, add Remove to jwk, and locking.

Play the coverage game

---

.github/workflows/ci.yml
.github/workflows/smoke.yml
jwk/ecdsa_gen.go
jwk/internal/cmd/genheader/main.go
jwk/okp_gen.go
jwk/rsa_gen.go
jwk/symmetric_gen.go

#330, but with the files generated, and CI actually enabled

---

Changes
jwk/ecdsa.go
jwk/jwk.go
jwk/jwk_test.go
jwk/rsa.go

incorporates fixes from #360, but adds further checks

Fix for invalid rsa and ecdsa keys being passed to jwk.New

---

jwt/internal/cmd/gentoken/main.go
jwt/openid/token_gen.go
jwt/token_gen.go

It was unused, and yet nobody (i.e. linters) complained

Remove jwt proxy object

---

README.md

super simple to use, excellent piece of go here.  thanks!

another typo...only because I love this package.

---

Changes
jwt/validate.go
jwt/validate_test.go

[jwt] Make jwt.Validate() return true for nbf == now

---

Changes
examples/jws_example_test.go
jws/jws.go
jws/jws_test.go

[jws] Change jws.VerifySet to return the key used to verify the payload

---

jwt/jwt_test.go

https://github.com/lestrrat-go/jwx/issues/384

Tests for #384

---

Changes
jwk/jwk_test.go
jwk/set.go

Fix key.Remove removing 2 elements

---

jwk/refresh.go

On second thought this is way more efficient than queuing up errors.

Do away with draining, discard error if write fails

---

jws/jws.go

Shave off 6 allocations
before
```
BenchmarkJWT/Serialization/Sign/jwt.Sign-24                          993           1207580 ns/op           36173 B/op        192 allocs/op
```
after
```
BenchmarkJWT/Serialization/Sign/jwt.Sign-24                          997           1194383 ns/op           35696 B/op        186 allocs/op
```

Reuse signer for given algorithm

---

jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

Be more explicit about requring `kid`

---

internal/pool/pool.go
jwt/http.go
jwt/jwt_test.go

Add better error messages when ParseHeader fails within ParseRequest

---

examples/jwt_example_test.go

added example to signed a JWT with a imported jwk
I had to spend a little time figuring out how to import a jwk. I believe the example can help other people who need to do the same. :)

chore: add example with import jwk

---

Changes
docs/01-jwt.md
examples/jwt_example_test.go
jwk/interface.go
jwk/interface_gen.go
jwk/internal/cmd/genheader/main.go
jwk/jwk.go
jws/jws.go
jws/jws_test.go
jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

[jwt] Add option for users to make JWT verification infer the `alg` field from JWKS

---

jwt/jwt_test.go

tests were inspired from comments in #472

Add tests to permute the location of the correct key in set

---

Changes
docs/01-jwt.md
jwt/options.go
jwt/validate.go
jwt/validate_test.go

Meanwhile also convert most everything in `jwt.Validate()` into `jwt.Validator` based implementation

Add option to pass arbitrary validation code

---

jwt/internal/cmd/gentoken/objects.yml
jwt/openid/openid_test.go
jwt/openid/token_gen.go

Fix openid claims, and actually test them

---

docs/01-jwt.md
jwt/validate.go
jwt/validate_test.go

Differentiate between validation errors and others

---

Changes
docs/04-jwk.md
jwk/interface.go
jwk/jwk.go
jwk/jwk_test.go
jwk/option.go
jwk/refresh.go
jwk/refresh_test.go
jwk/whitelist.go

Implement Whitelist

---

Changes
docs/02-jws.md
jws/jws.go
jws/jws_test.go
jws/option.go

[jws] Add ability to verify payload using "jku"

---

docs/01-jwt.md
docs/02-jws.md
jwk/jwk_test.go
jwk/whitelist.go
jws/jws.go
jws/jws_test.go
jws/option.go
jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

[jwt] Add options to enable verification via jws.VerifyAuto()

---

jws/jws.go
jws/jws_test.go
jws/option.go
jwt/jwt.go
jwt/jwt_test.go
jwt/options.go

Implement abstraction of jwk.Fetch in jws.VerifyAuto with JWKSetFetcher

---

jwk/refresh.go
jwk/refresh_test.go

[jwk] implement jwk.AutoRefresh.IsRegistered

---

.github/workflows/stale.yml

tweak stale messages

---

jwk/refresh.go
jwk/refresh_test.go

Implement (*jwk.AutoRefresh).Remove

---

jwt/http.go

jwt: fixed ParseRequest() documentation

---

docs/01-jwt.md
docs/99-faq.md
jwt/internal/cmd/gentoken/main.go
jwt/openid/token_gen.go
jwt/token_gen.go

Add documentation

---

jwe/internal/keyenc/interface.go
jwe/internal/keyenc/keyenc.go
jwe/jwe.go
jwe/jwe_test.go
jwe/message.go

Properly set the KeyID when receiving a jwk.Key

---

Changes
docs/02-jws.md
jws/ecdsa.go
jws/eddsa.go
jws/jws_test.go
jws/rsa.go

Fix verification for crypto.Signer

---

internal/cmd/genreadfile/go.mod
internal/cmd/genreadfile/main.go
jwa/internal/cmd/gentypes/go.mod
jwa/internal/cmd/gentypes/main.go
jwe/internal/cmd/genheader/go.mod
jwe/internal/cmd/genheader/main.go
jwk/internal/cmd/genheader/go.mod
jwk/internal/cmd/genheader/main.go
jws/internal/cmd/genheader/go.mod
jws/internal/cmd/genheader/main.go
jwt/internal/cmd/gentoken/go.mod
jwt/internal/cmd/gentoken/main.go

Switch error handling to fmt.Errorf for internal tools

---

Changes.v2
bench/performance/jwt_benchmark_test.go
docs/01-jwt.md
docs/02-jws.md
examples/jws_example_test.go
examples/jwt_example_test.go
internal/jwxtest/jwxtest.go
jws/jws.go
jws/jws_test.go
jws/key_provider.go
jws/option.go
jws/signer_test.go
jwt/jwt.go
jwt/jwt_test.go
jwt/openid/openid_test.go
jwt/options.go
jwt/serialize.go

Rework JWS/JWT Sign() method signatures

---

Changes.v2
jwe/jwe_test.go
jwe/message.go

Remove (jwe.Message).Decrypt

---

.github/workflows/autodoc.yml
docs/01-jwt.md
examples/snippets_jwt_parse_example_test.go
tools/autodocs.pl

Hand roll autodoc

---

.github/workflows/autodoc.yml
docs/01-jwt.md
examples/snippets_jwt_parse_example_test.go
tools/autodocs.pl

Handroll autodocs

---

Changes.v2
jwk/interface.go
jwk/jwk.go
jwk/options.yaml
jwk/options_gen.go
jwk/options_gen_test.go
jwk/refresh.go
jwk/refresh_test.go

Post fetch

---

.github/workflows/ci.yml
.github/workflows/smoke.yml
Changes-v2.md
go.mod

Up go dep as we said we did (oops)

---

jwt/validate.go

Removed unnecessary logging. (Remains by mistake?)

remove unnecessary logging

---

.github/workflows/lint.yml
Changes
jwk/interface_gen.go
tools/cmd/genjwk/objects.yml

Fix typo in x5u field name

---

docs/01-jwt.md
docs/02-jws.md
examples/jws_use_jws_header_test.go

[doc] Add notes about how to extract JWS headers

---

jws/jws_test.go

Make sure to clone the key

---

examples/jws_verify_detached_payload_example_test.go
examples/jws_verify_with_key_example_test.go

I have a feeling we inadvertently reverted some commit

fix example

---

Changes
docs/00-anatomy.md
docs/01-jwt.md
format.go
formatkind_string_gen.go
jwt/jwt.go
jwt/jwt_test.go

oops, some random document fixes went in as well.

Work with invalid JWT buffers better

---

jwk/jwk.go
jwk/jwk_test.go

Fix PEM armor for EC private keys when encoding

---

Changes
jws/jws.go
jws/jws_test.go
jws/message.go
jws/options.go
jws/signer.go
jwt/jwt_test.go
jwt/options.go
jwt/options.yaml
jwt/options_gen.go

Allow "none" algorithm when signing with explicit option

---

jwt/options.go

PS: Thanks for this library, it's incredibly useful and we are using it extensively in [Dapr](https://github.com/dapr/dapr) too

Fix typo in "jwt.WithAudience" comment

---

Changes
jwk/cache.go
jwk/fetch.go
jwk/jwk_test.go

Implement jwk.SetGlobalFetcher

---

Changes
jwk/jwk_test.go
jwk/key_ops.go

Accept a single KeyOperation in key.Set()

---

jwk/jwk_test.go
jwk/okp.go

Adam korcz fix 1

---

Changes
jwt/jwt_test.go
jwt/options.go

Adds a test to #952. Did verify that the issue exists before the patch and not after the patch using this test.
supersedes and closes #952

Add test case to #952

---

Changes
examples/jwt_parse_request_example_test.go
jwt/http.go
jwt/jwt_test.go
jwt/options.yaml
jwt/options_gen.go
jwt/options_gen_test.go

[jwt] Add cookie handling for jwt.ParseRequest()

---

Changes-v2.md
docs/04-jwk.md
docs/99-faq.md
jwk/cache.go
jwk/options.yaml
jwk/options_gen.go
jwk/refresh_test.go
jwk/whitelist.go
jws/jws_test.go
jwt/options.yaml
jwt/options_gen.go

The source files under generate are now modified.

fix: typos

---

jwk/jwk_test.go
jwt/jwt_test.go

Avoid problems on 32-bit systems

---

jwt/README.md

Revert "Fix link to openid"
